config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  get 'welcome/index'

  root 'welcome#index'
  
  resources :people

  resources :missions

  resources :teams

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mission.rb
class Mission < ApplicationRecord
  validates :title, presence: true, length: { minimum: 1}
  validates :challenge_label, length: { is: 1}

  def change
    create_table :missions do |t|
      t.string :title
      t.string :local
      t.string  :challenge_label
      t.integer :team
      t.string :creator
      t.text :comments
      t.integer :price


    end
  end


end

app/models/person.rb
class Person < ApplicationRecord
  validates :name, presence: true,
            length: { minimum: 3 }
  validates :username, presence: true
  validates :user_id, presence: true

  has_many :team_person1, :class_name => 'Team', :foreign_key => "person1_id"
  has_many :team_person2, :class_name => 'Team', :foreign_key => "person2_id"
  has_many :team_person3, :class_name => 'Team', :foreign_key => "person3_id"
  has_many :team_personsuperior, :class_name => 'Team', :foreign_key => "personsuperior_id"

end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :person1, :class_name => 'Person'
  belongs_to :person2, :class_name => 'Person'
  belongs_to :person3, :class_name => 'Person'
  belongs_to :personsuperior, :class_name => 'Person'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum access_level: [:solicitante, :ninja, :hokage]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  def index
    @mission = Mission.all
  end

  def show
    @mission = Mission.find(params[:id])
  end

  def new
     @mission = Mission.new
  end

  def edit
    @mission = Mission.find(params[:id])

  end

  def create
    @mission = Mission.new(mission_params)

    if @mission.save

    redirect_to @mission

    else render 'new'

    end
  end

  def update
    @mission = Mission.find(params[:id])

    if @mission.update(mission_params)
      redirect_to @mission
    else
      render 'edit'
    end
  end

  def destroy
    @mission = Mission.find(params[:id])
    @mission.destroy

    redirect_to missions_path
  end

private
  def mission_params
    params.require(:mission).permit(:title, :local, :challenge_label, :team, :creator, :comments, :price)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @person= Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
    @ranks = ['Genin', 'Chunin', 'Jounin', 'Hokage'] #Arruma os nomes que estão faltando, tem uma forma mais elegante, mas por enquanto isso serve bem
  end

  def edit
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(person_params)
    @ranks = ['Genin', 'Chunin', 'Jounin', 'Hokage']
    if @person.save
      redirect_to @person
    else
      render 'new'
    end

  end

  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to @person
    else
      render 'edit'
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    redirect_to people_path
  end

  private
  def person_params
    params.require(:person).permit(:name,:user_id,:birth_date,:home_address,:ninja_rank,:username,:user_type,:email)
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @team= Team.all
  end

  def show
    @team = Team.find(params[:id])
  end

  def new
    @team = Team.new
    @people = Person.all #recebemos todas as pessoas pra usar no select
    @chuninmais = Person.where('ninja_rank = ? or ninja_rank = ? or ninja_rank = ?', 'Chunin', 'Jounin', 'Hokage') #completa isso, dá uma olhada nesse formato ele faz um select no banco de dados com o parâmetro
  end

  def edit
    @team = Team.find(params[:id])
  end

  def create
    @people = Person.all
    team=team_params
    team[:person1_id]=Person.find(team_params[:person1_id])
    team[:person2_id]=Person.find(team_params[:person2_id])
    team[:person3_id]=Person.find(team_params[:person3_id])
    team[:personsuperior_id]=Person.find(team_params[:personsuperior_id])
    @team = Team.new(team)
    if @team.save
      redirect_to @team
    else
      render 'new'
    end

  end

  def update
    @team = Team.find(params[:id])
    if @team.update(team_params)
      redirect_to @team
    else
      render 'edit'
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    redirect_to teams_path
  end


  private
  def team_params
    params.require(:team).permit(:name,:person1_id,:person2_id,:person3_id,:personsuperior_id)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="#" class="brand-logo">Logo</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><a href="sass.html">Sass</a></li>
      <li><a href="badges.html">Components</a></li>
      <li><a href="collapsible.html">JavaScript</a></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KonohaMOS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/missions/_form.html.erb
<%= form_with model: @mission, local: true do |form| %>

    <% if @mission.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@mission.errors.count, "error") %> prohibited
            this mission from being saved:
          </h2>
          <ul>
            <% @mission.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="row">
      <div class="input-field col s6 l6 xl6">
        <%= form.text_field :title, autofocus: true, :required => true, :class => 'validate' %>
        <label for="title" class="active" data-error data-success>Title </label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6 l6 xl6">
        <%= form.text_field :local, autofocus: false, :required => true, :class => 'validate' %>
        <label for="local" class="active" data-error data-success>Local </label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6 l6 xl6">
        <%= form.text_field :challenge_label, autofocus: false, :required => true, :class => 'validate' %>
        <label for="challenge_label" class="active" data-error data-success>Challenge Level </label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6 l6 xl6">
        <%= form.text_field :team, autofocus: false, :required => true, :class => 'validate' %>
        <label for="team" class="active" data-error data-success>Team </label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6 l6 xl6">
        <%= form.text_field :creator, autofocus: false, :required => true, :class => 'validate' %>
        <label for="creator" class="active" data-error data-success>Creator </label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6 l6 xl6">
        <%= form.text_field :comments, autofocus: false, :required => true, :class => 'validate' %>
        <label for="comments" class="active" data-error data-success>Comments </label>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6 l6 xl6">
        <%= form.text_field :price, autofocus: false, :required => true, :class => 'validate' %>
        <label for="price" class="active" data-error data-success>price </label>
      </div>
    </div>

    <p>
      <%= form.submit %>
    </p>

<% end %>

app/views/missions/edit.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="#" class="brand-logo">Logo</a>
    <ul class="right hide-on-med-and-down">
      <li><a href="/missions.html">Missions</a></li>
      <li><a href="/people.html">People</a></li>
      <li><a href="/teams.html">Teams</a></li>

    </ul>
  </div>
</nav>

<body>
<div class="container">
  <h1>Edit mission</h1>

  <%= render 'form'%>
  <%= link_to 'Back', missions_path %>

</div>
</body>

app/views/missions/index.html.erb
<nav>
  <div class="nav-wrapper">
    <ul class="left hide-on-med-and-down">
      <li><a href=/# >back</a></li>
    </ul>
    <a href="#" class="brand-logo">Logo</a>
    <ul class="right hide-on-med-and-down">
      <li><a href="missions.html">Missions</a></li>
      <li><a href="people.html">People</a></li>
      <li><a href="teams.html">Teams</a></li>

    </ul>
  </div>
</nav>

<body>
<div class="container">
  <h1>Missions</h1>

  <table>
    <thead>
    <tr>
      <th>Title</th>
      <th>Teams</th>
    </tr>
    </thead>

    <% @mission.each do |mission| %>
        <tbody>
        <tr>
          <td><%=mission.title%></mission.title></td>
          <td><%=mission.team%></td>
          <td><a class="waves-effect waves-light btn" href = "/missions/<%=mission.id%>"> Show </a></td>
          <td><a class="waves-effect waves-light btn" href = "/missions/<%=mission.id%>/edit"> Edit </a></td>
          <td><%= button_to 'destroy', mission_path(mission), method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
        </tbody>
    <%end%>
  </table>
  <a class="waves-effect waves-light btn" href="missions/new">New mission</a>

</div>
</body>

app/views/missions/new.html.erb
<body>
<div class="container">
  <h1>New Mission</h1>

  <%= render 'form'%>
  <a class="waves-effect waves-light btn" href="/missions.html">Back</a>
</div>
</body>

app/views/missions/show.html.erb
<body>
<div class="container">
  <ul class="collection">
  <li class="collection-item">
    <p>
  <strong>Title:</strong>
  <%= @mission.title %>
  </p>
    </li>

  <li class="collection-item">
    <p>
    <strong>Local:</strong>
    <%= @mission.local %>
  </p>
    </li>

  <li class="collection-item">
    <p>
    <strong>Challenge Level:</strong>
    <%= @mission.challenge_label %>
  </p>
    </li>

  <li class="collection-item">
    <p>
    <strong>Team:</strong>
    <%= @mission.team %>
  </p>
    </li>

  <li class="collection-item">
    <p>
    <strong>Creator:</strong>
    <%= @mission.creator %>
  </p>
    </li>

  <li class="collection-item">
    <p>
    <strong>Commments:</strong>
    <%= @mission.comments %>
  </p>
    </li>

  <li class="collection-item">
    <p>
    <strong>Price:</strong>
    <%= @mission.price %>
  </p>
  </li>
  </ul>
  <a class="waves-effect waves-light btn" href="/missions">Back</a>

        
</div>

</body>

app/views/people/_form.html.erb
isso é pro select funcionar com materialize <%= form_with model: @person, local: true do |form| %> <% if @person.errors.any? %>
        <%= pluralize(@person.errors.count, "error") %> prohibited this article from being saved:

        <% @person.errors.full_messages.each do |msg| %>
            <%= msg %>
        <% end %>
    <% end %>
    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.label :user_id %>
    <%= form.text_area :user_id %>

    <%= form.label :birth_date %>
    <%= form.text_area :birth_date %>

    <%= form.label :home_address %>
    <%= form.text_area :home_address %>

    <%= form.label :ninja_rank %>
    <%= form.select :ninja_rank, @ranks %>

    <%= form.label :username %>
    <%= form.text_area :username %>

    <%= form.label :user_type %>
    <%= form.text_area :user_type %>

    <%= form.label :email %>
    <%= form.text_area :email %>

    <%= form.submit %>

<% end %>

app/views/people/edit.html.erb
<body>
<div class="container">
  <h1>Edit Person</h1>

  <%= render 'form' %>

  <%= link_to 'Back', people_path %>
</div>
</body>

app/views/people/index.html.erb
<nav>
  <div class="nav-wrapper">
    <ul class="left hide-on-med-and-down">
      <li><a href=/# >back</a></li>
    </ul>
    <a href="#" class="brand-logo">Logo</a>
    <ul class="right hide-on-med-and-down">
      <li><a href="missions.html">Missions</a></li>
      <li><a href="people.html">People</a></li>
      <li><a href="teams.html">Teams</a></li>

    </ul>
  </div>
</nav>

<body>
<div class="container">
  <h1>Ninjas</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>User Id</th>
      </tr>
    </thead>

    <% @person.each do |person| %>
        <tbody>
          <tr>
            <td><%=person.name%></mission.title></td>
            <td><%=person.id%></td>
            <td><a class="waves-effect waves-light btn" href = "/people/<%=person.id%>"> Show </a></td>
            <td><a class="waves-effect waves-light btn" href = "/people/<%=person.id%>/edit"> Edit </a></td>

            <td><%= button_to 'destroy',person_path(person),
                            method: :delete,
                            data: { confirm: 'Are you sure?'} %> </td>
          </tr>
        </tbody>
    <%end%>
</table>
  <a class="waves-effect waves-light btn" href="people/new.html">New person</a>

</div>
</body>

app/views/people/new.html.erb
<body>
<div class="container">
  <h1>New Person</h1>

  <%= render 'form' %>

  <a class="waves-effect waves-light btn" href="/people.html">Back</a>
</div>
</body>

app/views/people/show.html.erb
<body>
<div class="container">
  <ul class="collection">
    <li class="collection-item">
    <p>
      <strong>Name:</strong>
      <%= @person.name %>
     </p>
    </li>

    <li class="collection-item">
      <p>
        <strong>Id:</strong>
        <%= @person.user_id %>
      </p>
    </li>

    <li class="collection-item">
      <p>
        <strong>Birth date:</strong>
        <%= @person.birth_date %>
      </p>
    </li>

    <li class="collection-item">
      <p>
      <strong>Home address:</strong>
      <%= @person.home_address %>
      </p>
    </li>

    <li class="collection-item">
      <p>
        <strong>Ninja rank:</strong>
        <%= @person.ninja_rank %>
      </p>
    </li>

    <li class="collection-item">
      <p>
        <strong>username:</strong>
        <%= @person.username %>
      </p>
    </li>
    <li class="collection-item">
      <p>
      <strong>email:</strong>
      <%= @person.email %>
      </p>
    </li>

  </ul>
  <a class="waves-effect waves-light btn" href="/people.html">Back</a>
</div>
</body>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <h3>Welcome</h3>
<% end %>

<% if current_user != nil %>
<% if current_user.hokage? %>
  <h3>Welcome Hokage</h3>
<% elsif current_user.ninja? %>
  <h3>Welcome, Ninja</h3>
<% else %>
  <h3>Welcome</h3>
<% end %>
<% end %>

<%= link_to 'My Missions', controller: 'missions' %>
<%= link_to 'People', controller: 'people' %>
<%= link_to 'Teams', controller: 'teams' %>